### ISSUE TITLE
Address removal frame

### ISSUE THREAD

**Issue by MedAlexey** [MedAlexey/autotest2019#24]
##  Имя класса
RemovalAddressFrame

## Методы
* delete - нажать кнопку "удалить"

## Страница, которую описывает класс

![изображение](https://user-images.githubusercontent.com/22035174/57979552-9acf7800-7a49-11e9-840f-b6f73aa8cf5e.png)

**Comment by nik27090** [comment]
Когда остается один адрес, его нельзя удалить
