### ISSUE TITLE
User main page

### ISSUE THREAD

**Issue by MedAlexey** [MedAlexey/autotest2019#7]
## Имя класса
UserMainPage

## Методы 

* openGoods() - открыть страницу товаров
   * return GoodsPage

* openMessages() - открыть сообщения
   * return MessagesPage

* checkProduct (IProductPage (см. #6 )) - проверка наличия на стене пользователя определённого товара
   * return boolean

**Comment by MedAlexey** [comment]
Похоже, что `chaeckProduct()` должен возвращать promise.

**Comment by nik27090** [comment]
Проблема, на стене пользователя нельзя взять название товара, нужно кликнуть по продукту и открыть леер с товаром, там уже провести проверку

**Comment by MedAlexey** [comment]
ок, добавлю метод получения названия в страницу товара.

**Comment by nik27090** [comment]
Не надо! Сделал так чтоб метод checkProduct открывал леер, проверял название и сразу же закрывал его, вроде, если пэйдж после закрытия леера не перестраивается, можно так делать
